# Generated by Django 5.2.6 on 2026-10-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookreservation',
            name='unique_book_reservation_user_book',
        ),
        migrations.RemoveConstraint(
            model_name='favorite_book',
            name='unique_favorite_user_book',
        ),
        migrations.RemoveConstraint(
            model_name='quotelike',
            name='unique_quote_like_per_user',
        ),
        migrations.RemoveField(
            model_name='bookreservation',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookreservation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='booksummary',
            name='book',
        ),
        migrations.RemoveField(
            model_name='booksummary',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favorite_book',
            name='book',
        ),
        migrations.RemoveField(
            model_name='favorite_book',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quotelike',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='quotelike',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookRating',
        ),
        migrations.DeleteModel(
            name='BookReservation',
        ),
        migrations.DeleteModel(
            name='BookSummary',
        ),
        migrations.DeleteModel(
            name='Favorite_Book',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='QuoteLike',
        ),
    ]
