# Generated by Django 5.2.6 on 2025-10-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_borrowedbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
