# Generated by Django 5.2.6 on 2025-10-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_category_book_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='Category',
        ),
    ]
