# Generated by Django 5.2.6 on 2025-10-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_category_book_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Category',
            new_name='category',
        ),
    ]
