# Generated by Django 5.2.6 on 2025-10-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_category_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='possition',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
