# Generated by Django 5.2.6 on 2025-11-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='return_request',
            field=models.BooleanField(default=False),
        ),
    ]
