# Generated by Django 5.2.6 on 2025-11-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='isbn',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='publication_year',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
