# Generated by Django 5.2.6 on 2025-11-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_borrowedbook_isbn_borrowedbook_publication_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='publication_year',
            field=models.IntegerField(null=True),
        ),
    ]
