# Generated by Django 5.2.6 on 2025-11-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_borrowedbook_publication_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='borrowedbook',
            name='publication_year',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(null=True),
        ),
    ]
