# Generated by Django 5.2.6 on 2025-11-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copies',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
