# Generated by Django 5.2.6 on 2025-11-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_book_copies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='copies',
            new_name='available_copies',
        ),
    ]
