# Generated by Django 5.2.6 on 2025-11-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_rename_copies_book_available_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count_borrowed',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
