# Generated by Django 5.2.6 on 2025-12-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_book_count_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='return_request_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
