# Generated by Django 5.2.6 on 2025-12-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_borrowedbook_return_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='late_day',
            field=models.IntegerField(default=0),
        ),
    ]
