# Generated by Django 5.2.6 on 2025-12-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_borrowedbook_due_date_borrowedbook_late_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrow_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
