# Generated by Django 5.2.6 on 2025-12-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_alter_borrowedbook_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrow_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
