# Generated by Django 5.2.6 on 2025-12-11 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_alter_borrowedbook_borrow_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='late_day',
        ),
    ]
