# Generated by Django 5.2.6 on 2026-02-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_rename_customuser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
