# Generated by Django 5.2.6 on 2026-05-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_quote_quotelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='extension_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='extension_request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='is_extended',
            field=models.BooleanField(default=False),
        ),
    ]
