# Generated by Django 5.2.6 on 2026-10-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activityregistration',
            name='unique_activity_registration',
        ),
        migrations.RemoveField(
            model_name='activityregistration',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activityregistration',
            name='user',
        ),
        migrations.DeleteModel(
            name='LibraryActivity',
        ),
        migrations.DeleteModel(
            name='ActivityRegistration',
        ),
    ]
