# Generated by Django 5.2.6 on 2026-10-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='accounts_user_role_scope_valid',
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('is_superuser', True), models.Q(('governorate__isnull', True), ('library__isnull', True), ('role', 'MINISTRY_ADMIN')), models.Q(('governorate__isnull', False), ('library__isnull', True), ('role', 'GOVERNORATE_ADMIN')), models.Q(('governorate__isnull', True), ('library__isnull', False), ('role', 'LIBRARIAN')), models.Q(('governorate__isnull', True), ('library__isnull', False), ('role', 'READER')), _connector='OR'), name='accounts_user_role_scope_valid'),
        ),
    ]
