# Generated by Django 5.2.6 on 2026-05-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='borrowing_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
